print("Second |Half Action")
print("=================")
input("Enter the home team halftime score:")
input("Enter the home team halftime score:")
print()
input("Enter the home team full time score:")
input("Enter the away team full time score:")
print()
print("The total number of goals scored after halftime is:")
print("<<totalgoals>>")